var e4_questions = {
    "questions": [
        {
            "id": "E4A01",
            "question": "Which of the following limits the highest frequency signal that can be accurately displayed on a digital oscilloscope?",
            "options": [
                "A. Sampling rate of the analog-to-digital converter",
                "B. Analog-to-digital converter reference frequency",
                "C. Q of the circuit",
                "D. All these choices are correct"
            ],
            "answer": "A. Sampling rate of the analog-to-digital converter"
        },
        {
            "id": "E4A02",
            "question": "Which of the following parameters does a spectrum analyzer display on the vertical and horizontal axes?",
            "options": [
                "A. Signal amplitude and time",
                "B. Signal amplitude and frequency",
                "C. SWR and frequency",
                "D. SWR and time"
            ],
            "answer": "B. Signal amplitude and frequency"
        },
        {
            "id": "E4A03",
            "question": "Which of the following test instruments is used to display spurious signals and/or intermodulation distortion products generated by an SSB transmitter?",
            "options": [
                "A. Differential resolver",
                "B. Spectrum analyzer",
                "C. Logic analyzer",
                "D. Network analyzer"
            ],
            "answer": "B. Spectrum analyzer"
        },
        {
            "id": "E4A04",
            "question": "How is compensation of an oscilloscope probe performed?",
            "options": [
                "A. A square wave is displayed, and the probe is adjusted until the horizontal portions of the displayed wave are as nearly flat as possible",
                "B. A high frequency sine wave is displayed, and the probe is adjusted for maximum amplitude",
                "C. A frequency standard is displayed, and the probe is adjusted until the deflection time is accurate",
                "D. A DC voltage standard is displayed, and the probe is adjusted until the displayed voltage is accurate"
            ],
            "answer": "A. A square wave is displayed, and the probe is adjusted until the horizontal portions of the displayed wave are as nearly flat as possible"
        },
        {
            "id": "E4A05",
            "question": "What is the purpose of using a prescaler with a frequency counter?",
            "options": [
                "A. Amplify low-level signals for more accurate counting",
                "B. Multiply a higher frequency signal so a low-frequency counter can display the operating frequency",
                "C. Prevent oscillation in a low-frequency counter circuit",
                "D. Reduce the signal frequency to within the counter's operating range"
            ],
            "answer": "D. Reduce the signal frequency to within the counter's operating range"
        },
        {
            "id": "E4A06",
            "question": "What is the effect of aliasing on a digital oscilloscope when displaying a waveform?",
            "options": [
                "A. A false, jittery low-frequency version of the waveform is displayed",
                "B. The waveform DC offset will be inaccurate",
                "C. Calibration of the vertical scale is no longer valid",
                "D. Excessive blanking occurs, which prevents display of the waveform"
            ],
            "answer": "A. A false, jittery low-frequency version of the waveform is displayed"
        },
        {
            "id": "E4A07",
            "question": "Which of the following is an advantage of using an antenna analyzer compared to an SWR bridge?",
            "options": [
                "A. Antenna analyzers automatically tune your antenna for resonance",
                "B. Antenna analyzers compute SWR and impedance automatically",
                "C. Antenna analyzers display a time-varying representation of the modulation envelope",
                "D. All these choices are correct"
            ],
            "answer": "B. Antenna analyzers compute SWR and impedance automatically"
        },
        {
            "id": "E4A08",
            "question": "Which of the following is used to measure SWR?",
            "options": [
                "A. Directional wattmeter",
                "B. Vector network analyzer",
                "C. Antenna analyzer",
                "D. All these choices are correct"
            ],
            "answer": "D. All these choices are correct"
        },
        {
            "id": "E4A09",
            "question": "Which of the following is good practice when using an oscilloscope probe?",
            "options": [
                "A. Minimize the length of the probe's ground connection",
                "B. Never use a high-impedance probe to measure a low-impedance circuit",
                "C. Never use a DC-coupled probe to measure an AC circuit",
                "D. All these choices are correct"
            ],
            "answer": "A. Minimize the length of the probe's ground connection"
        },
        {
            "id": "E4A10",
            "question": "Which trigger mode is most effective when using an oscilloscope to measure a linear power supply’s output ripple?",
            "options": [
                "A. Single-shot",
                "B. Edge",
                "C. Level",
                "D. Line"
            ],
            "answer": "D. Line"
        },
        {
            "id": "E4A11",
            "question": "Which of the following can be measured with an antenna analyzer?",
            "options": [
                "A. Velocity factor",
                "B. Cable length",
                "C. Resonant frequency of a tuned circuit",
                "D. All these choices are correct"
            ],
            "answer": "D. All these choices are correct"
        },
        {
            "id": "E4B01",
            "question": "Which of the following factors most affects the accuracy of a frequency counter?",
            "options": [
                "A. Input attenuator accuracy",
                "B. Time base accuracy",
                "C. Decade divider accuracy",
                "D. Temperature coefficient of the logic"
            ],
            "answer": "B. Time base accuracy"
        },
        {
            "id": "E4B02",
            "question": "What is the significance of voltmeter sensitivity expressed in ohms per volt?",
            "options": [
                "A. The full scale reading of the voltmeter multiplied by its ohms per volt rating is the input impedance of the voltmeter",
                "B. The reading in volts multiplied by the ohms per volt rating will determine the power drawn by the device under test",
                "C. The reading in ohms divided by the ohms per volt rating will determine the voltage applied to the circuit",
                "D. The full scale reading in amps divided by ohms per volt rating will determine the size of shunt needed"
            ],
            "answer": "A. The full scale reading of the voltmeter multiplied by its ohms per volt rating is the input impedance of the voltmeter"
        },
        {
            "id": "E4B03",
            "question": "Which S parameter is equivalent to forward gain?",
            "options": [
                "A. S11",
                "B. S12",
                "C. S21",
                "D. S22"
            ],
            "answer": "C. S21"
        },
        {
            "id": "E4B04",
            "question": "Which S parameter represents input port return loss or reflection coefficient (equivalent to VSWR)?",
            "options": [
                "A. S11",
                "B. S12",
                "C. S21",
                "D. S22"
            ],
            "answer": "A. S11"
        },
        {
            "id": "E4B05",
            "question": "What three test loads are used to calibrate an RF vector network analyzer?",
            "options": [
                "A. 50 ohms, 75 ohms, and 90 ohms",
                "B. Short circuit, open circuit, and 50 ohms",
                "C. Short circuit, open circuit, and resonant circuit",
                "D. 50 ohms through 1/8 wavelength, 1/4 wavelength, and 1/2 wavelength of coaxial cable"
            ],
            "answer": "B. Short circuit, open circuit, and 50 ohms"
        },
        {
            "id": "E4B06",
            "question": "How much power is being absorbed by the load when a directional power meter connected between a transmitter and a terminating load reads 100 watts forward power and 25 watts reflected power?",
            "options": [
                "A. 100 watts",
                "B. 125 watts",
                "C. 112.5 watts",
                "D. 75 watts"
            ],
            "answer": "D. 75 watts"
        },
        {
            "id": "E4B07",
            "question": "What do the subscripts of S parameters represent?",
            "options": [
                "A. The port or ports at which measurements are made",
                "B. The relative time between measurements",
                "C. Relative quality of the data",
                "D. Frequency order of the measurements"
            ],
            "answer": "A. The port or ports at which measurements are made"
        },
        {
            "id": "E4B08",
            "question": "Which of the following can be used to determine the Q of a series-tuned circuit?",
            "options": [
                "A. The ratio of inductive reactance to capacitive reactance",
                "B. The frequency shift",
                "C. The bandwidth of the circuit's frequency response",
                "D. The resonant frequency of the circuit"
            ],
            "answer": "C. The bandwidth of the circuit's frequency response"
        },
        {
            "id": "E4B09",
            "question": "Which of the following can be measured by a two-port vector network analyzer?",
            "options": [
                "A. Phase noise",
                "B. Filter frequency response",
                "C. Pulse rise time",
                "D. Forward power"
            ],
            "answer": "B. Filter frequency response"
        },
        {
            "id": "E4B10",
            "question": "Which of the following methods measures intermodulation distortion in an SSB transmitter?",
            "options": [
                "A. Modulate the transmitter using two RF signals having non-harmonically related frequencies and observe the RF output with a spectrum analyzer",
                "B. Modulate the transmitter using two AF signals having non-harmonically related frequencies and observe the RF output with a spectrum analyzer",
                "C. Modulate the transmitter using two AF signals having harmonically related frequencies and observe the RF output with a peak reading wattmeter",
                "D. Modulate the transmitter using two RF signals having harmonically related frequencies and observe the RF output with a logic analyzer"
            ],
            "answer": "B. Modulate the transmitter using two AF signals having non-harmonically related frequencies and observe the RF output with a spectrum analyzer"
        },
        {
            "id": "E4B11",
            "question": "Which of the following can be measured with a vector network analyzer?",
            "options": [
                "A. Input impedance",
                "B. Output impedance",
                "C. Reflection coefficient",
                "D. All these choices are correct"
            ],
            "answer": "D. All these choices are correct"
        },
        {
            "id": "E4C01",
            "question": "What is an effect of excessive phase noise in an SDR receiver’s master clock oscillator?",
            "options": [
                "A. It limits the receiver’s ability to receive strong signals",
                "B. It can affect the receiver’s frequency calibration",
                "C. It decreases the receiver’s third-order intercept point",
                "D. It can combine with strong signals on nearby frequencies to generate interference"
            ],
            "answer": "D. It can combine with strong signals on nearby frequencies to generate interference"
        },
        {
            "id": "E4C02",
            "question": "Which of the following receiver circuits can be effective in eliminating interference from strong out-of-band signals?",
            "options": [
                "A. A front-end filter or preselector",
                "B. A narrow IF filter",
                "C. A notch filter",
                "D. A properly adjusted product detector"
            ],
            "answer": "A. A front-end filter or preselector"
        },
        {
            "id": "E4C03",
            "question": "What is the term for the suppression in an FM receiver of one signal by another stronger signal on the same frequency?",
            "options": [
                "A. Desensitization",
                "B. Cross-modulation interference",
                "C. Capture effect",
                "D. Frequency discrimination"
            ],
            "answer": "C. Capture effect"
        },
        {
            "id": "E4C04",
            "question": "What is the noise figure of a receiver?",
            "options": [
                "A. The ratio of atmospheric noise to phase noise",
                "B. The ratio of the noise bandwidth in hertz to the theoretical bandwidth of a resistive network",
                "C. The ratio in dB of the noise generated in the receiver to atmospheric noise",
                "D. The ratio in dB of the noise generated by the receiver to the theoretical minimum noise"
            ],
            "answer": "D. The ratio in dB of the noise generated by the receiver to the theoretical minimum noise"
        },
        {
            "id": "E4C05",
            "question": "What does a receiver noise floor of -174 dBm represent?",
            "options": [
                "A. The receiver noise is 6 dB above the theoretical minimum",
                "B. The theoretical noise in a 1 Hz bandwidth at the input of a perfect receiver at room temperature",
                "C. The noise figure of a 1 Hz bandwidth receiver",
                "D. The receiver noise is 3 dB above theoretical minimum"
            ],
            "answer": "B. The theoretical noise in a 1 Hz bandwidth at the input of a perfect receiver at room temperature"
        },
        {
            "id": "E4C06",
            "question": "How much does increasing a receiver’s bandwidth from 50 Hz to 1,000 Hz increase the receiver’s noise floor?",
            "options": [
                "A. 3 dB",
                "B. 5 dB",
                "C. 10 dB",
                "D. 13 dB"
            ],
            "answer": "D. 13 dB"
        },
        {
            "id": "E4C07",
            "question": "What does the MDS of a receiver represent?",
            "options": [
                "A. The meter display sensitivity",
                "B. The minimum discernible signal",
                "C. The modulation distortion specification",
                "D. The maximum detectable spectrum"
            ],
            "answer": "B. The minimum discernible signal"
        },
        {
            "id": "E4C08",
            "question": "An SDR receiver is overloaded when input signals exceed what level?",
            "options": [
                "A. One-half of the maximum sample rate",
                "B. One-half of the maximum sampling buffer size",
                "C. The maximum count value of the analog-to-digital converter",
                "D. The reference voltage of the analog-to-digital converter"
            ],
            "answer": "D. The reference voltage of the analog-to-digital converter"
        },
        {
            "id": "E4C09",
            "question": "Which of the following choices is a good reason for selecting a high IF for a superheterodyne HF or VHF communications receiver?",
            "options": [
                "A. Fewer components in the receiver",
                "B. Reduced drift",
                "C. Easier for front-end circuitry to eliminate image responses",
                "D. Improved receiver noise figure"
            ],
            "answer": "C. Easier for front-end circuitry to eliminate image responses"
        },
        {
            "id": "E4C10",
            "question": "What is an advantage of having a variety of receiver bandwidths from which to select?",
            "options": [
                "A. The noise figure of the RF amplifier can be adjusted to match the modulation type, thus increasing receiver sensitivity",
                "B. Receiver power consumption can be reduced when wider bandwidth is not required",
                "C. Receive bandwidth can be set to match the modulation bandwidth, maximizing signal-to-noise ratio and minimizing interference",
                "D. Multiple frequencies can be received simultaneously if desired"
            ],
            "answer": "C. Receive bandwidth can be set to match the modulation bandwidth, maximizing signal-to-noise ratio and minimizing interference"
        },
        {
            "id": "E4C11",
            "question": "Why does input attenuation reduce receiver overload on the lower frequency HF bands with little or no impact on signal-to-noise ratio?",
            "options": [
                "A. The attenuator has a low-pass filter to increase the strength of lower frequency signals",
                "B. The attenuator has a noise filter to suppress interference",
                "C. Signals are attenuated separately from the noise",
                "D. Atmospheric noise is generally greater than internally generated noise even after attenuation"
            ],
            "answer": "D. Atmospheric noise is generally greater than internally generated noise even after attenuation"
        },
        {
            "id": "E4C12",
            "question": "How does a narrow-band roofing filter affect receiver performance?",
            "options": [
                "A. It improves sensitivity by reducing front-end noise",
                "B. It improves intelligibility by using low Q circuitry to reduce ringing",
                "C. It improves blocking dynamic range by attenuating strong signals near the receive frequency",
                "D. All these choices are correct"
            ],
            "answer": "C. It improves blocking dynamic range by attenuating strong signals near the receive frequency"
        },
        {
            "id": "E4C13",
            "question": "What is reciprocal mixing?",
            "options": [
                "A. Two out-of-band signals mixing to generate an in-band spurious signal",
                "B. In-phase signals cancelling in a mixer resulting in loss of receiver sensitivity",
                "C. Two digital signals combining from alternate time slots",
                "D. Local oscillator phase noise mixing with adjacent strong signals to create interference to desired signals"
            ],
            "answer": "D. Local oscillator phase noise mixing with adjacent strong signals to create interference to desired signals"
        },
        {
            "id": "E4C14",
            "question": "What is the purpose of the receiver IF Shift control?",
            "options": [
                "A. To permit listening on a different frequency from the transmitting frequency",
                "B. To change frequency rapidly",
                "C. To reduce interference from stations transmitting on adjacent frequencies",
                "D. To tune in stations slightly off frequency without changing the transmit frequency"
            ],
            "answer": "C. To reduce interference from stations transmitting on adjacent frequencies"
        },
        {
            "id": "E4D01",
            "question": "What is meant by the blocking dynamic range of a receiver?",
            "options": [
                "A. The difference in dB between the noise floor and the level of an incoming signal that will cause 1 dB of gain compression",
                "B. The minimum difference in dB between the levels of two FM signals that will cause one signal to block the other",
                "C. The difference in dB between the noise floor and the third-order intercept point",
                "D. The minimum difference in dB between two signals which produce third-order intermodulation products greater than the noise floor"
            ],
            "answer": "A. The difference in dB between the noise floor and the level of an incoming signal that will cause 1 dB of gain compression"
        },
        {
            "id": "E4D02",
            "question": "Which of the following describes problems caused by poor dynamic range in a receiver?",
            "options": [
                "A. Spurious signals caused by cross modulation and desensitization from strong adjacent signals",
                "B. Oscillator instability requiring frequent retuning and loss of ability to recover the opposite sideband",
                "C. Poor weak signal reception caused by insufficient local oscillator injection",
                "D. Oscillator instability and severe audio distortion of all but the strongest received signals"
            ],
            "answer": "A. Spurious signals caused by cross modulation and desensitization from strong adjacent signals"
        },
        {
            "id": "E4D03",
            "question": "What creates intermodulation interference between two repeaters in close proximity?",
            "options": [
                "A. The output signals cause feedback in the final amplifier of one or both transmitters",
                "B. The output signals mix in the final amplifier of one or both transmitters",
                "C. The input frequencies are harmonically related",
                "D. The output frequencies are harmonically related"
            ],
            "answer": "B. The output signals mix in the final amplifier of one or both transmitters"
        },
        {
            "id": "E4D04",
            "question": "Which of the following is used to reduce or eliminate intermodulation interference in a repeater caused by a nearby transmitter?",
            "options": [
                "A. A band-pass filter in the feed line between the transmitter and receiver",
                "B. A properly terminated circulator at the output of the repeater’s transmitter",
                "C. Utilizing a Class C final amplifier",
                "D. Utilizing a Class D final amplifier"
            ],
            "answer": "B. A properly terminated circulator at the output of the repeater’s transmitter"
        },
        {
            "id": "E4D05",
            "question": "What transmitter frequencies would create an intermodulation-product signal in a receiver tuned to 146.70 MHz when a nearby station transmits on 146.52 MHz?",
            "options": [
                "A. 146.34 MHz and 146.61 MHz",
                "B. 146.88 MHz and 146.34 MHz",
                "C. 146.10 MHz and 147.30 MHz",
                "D. 146.30 MHz and 146.90 MHz"
            ],
            "answer": "A. 146.34 MHz and 146.61 MHz"
        },
        {
            "id": "E4D06",
            "question": "What is the term for the reduction in receiver sensitivity caused by a strong signal near the received frequency?",
            "options": [
                "A. Reciprocal mixing",
                "B. Quieting",
                "C. Desensitization",
                "D. Cross modulation interference"
            ],
            "answer": "C. Desensitization"
        },
        {
            "id": "E4D07",
            "question": "Which of the following reduces the likelihood of receiver desensitization?",
            "options": [
                "A. Insert attenuation before the first RF stage",
                "B. Raise the receiver’s IF frequency",
                "C. Increase the receiver’s front-end gain",
                "D. Switch from fast AGC to slow AGC"
            ],
            "answer": "A. Insert attenuation before the first RF stage"
        },
        {
            "id": "E4D08",
            "question": "What causes intermodulation in an electronic circuit?",
            "options": [
                "A. Negative feedback",
                "B. Lack of neutralization",
                "C. Nonlinear circuits or devices",
                "D. Positive feedback"
            ],
            "answer": "C. Nonlinear circuits or devices"
        },
        {
            "id": "E4D09",
            "question": "What is the purpose of the preselector in a communications receiver?",
            "options": [
                "A. To store frequencies that are often used",
                "B. To provide broadband attenuation before the first RF stage to prevent intermodulation",
                "C. To increase the rejection of signals outside the band being received",
                "D. To allow selection of the optimum RF amplifier device"
            ],
            "answer": "C. To increase the rejection of signals outside the band being received"
        },
        {
            "id": "E4D10",
            "question": "What does a third-order intercept level of 40 dBm mean with respect to receiver performance?",
            "options": [
                "A. Signals less than 40 dBm will not generate audible third-order intermodulation products",
                "B. The receiver can tolerate signals up to 40 dB above the noise floor without producing third-order intermodulation products",
                "C. A pair of 40 dBm input signals will theoretically generate a third-order intermodulation product that has the same output amplitude as either of the input signals",
                "D. A pair of 1 mW input signals will produce a third-order intermodulation product that is 40 dB stronger than the input signal"
            ],
            "answer": "C. A pair of 40 dBm input signals will theoretically generate a third-order intermodulation product that has the same output amplitude as either of the input signals"
        },
        {
            "id": "E4D11",
            "question": "Why are odd-order intermodulation products, created within a receiver, of particular interest compared to other products?",
            "options": [
                "A. Odd-order products of two signals in the band being received are also likely to be within the band",
                "B. Odd-order products are more likely to overload the IF filters",
                "C. Odd-order products are an indication of poor image rejection",
                "D. Odd-order intermodulation produces three products for every input signal within the band of interest"
            ],
            "answer": "A. Odd-order products of two signals in the band being received are also likely to be within the band"
        },
        {
            "id": "E4D12",
            "question": "What is the link margin in a system with a transmit power level of 10 W (+40 dBm), a system antenna gain of 10 dBi, a cable loss of 3 dB, a path loss of 136 dB, a receiver minimum discernable signal of -103 dBm, and a required signal-to-noise ratio of 6 dB?",
            "options": [
                "A. -8dB",
                "B. -14dB",
                "C. +8dB",
                "D. +14dB"
            ],
            "answer": "C. +8dB"
        },
        {
            "id": "E4D13",
            "question": "What is the received signal level with a transmit power of 10 W (+40 dBm), a transmit antenna gain of 6 dBi, a receive antenna gain of 3 dBi, and a path loss of 100 dB?",
            "options": [
                "A. -51 dBm",
                "B. -54 dBm",
                "C. -57 dBm",
                "D. -60 dBm"
            ],
            "answer": "A. -51 dBm"
        },
        {
            "id": "E4D14",
            "question": "What power level does a receiver minimum discernible signal of -100 dBm represent?",
            "options": [
                "A. 100 microwatts",
                "B. 0.1 microwatt",
                "C. 0.001 microwatts",
                "D. 0.1 picowatts"
            ],
            "answer": "D. 0.1 picowatts"
        },
        {
            "id": "E4E01",
            "question": "What problem can occur when using an automatic notch filter (ANF) to remove interfering carriers while receiving CW signals?",
            "options": [
                "A. Removal of the CW signal as well as the interfering carrier",
                "B. Any nearby signal passing through the DSP system will overwhelm the desired signal",
                "C. Excessive ringing",
                "D. All these choices are correct"
            ],
            "answer": "A. Removal of the CW signal as well as the interfering carrier"
        },
        {
            "id": "E4E02",
            "question": "Which of the following types of noise can often be reduced by a digital noise reduction?",
            "options": [
                "A. Broadband white noise",
                "B. Ignition noise",
                "C. Power line noise",
                "D. All these choices are correct"
            ],
            "answer": "D. All these choices are correct"
        },
        {
            "id": "E4E03",
            "question": "Which of the following types of noise are removed by a noise blanker?",
            "options": [
                "A. Broadband white noise",
                "B. Impulse noise",
                "C. Hum and buzz",
                "D. All these choices are correct"
            ],
            "answer": "B. Impulse noise"
        },
        {
            "id": "E4E04",
            "question": "How can conducted noise from an automobile battery charging system be suppressed?",
            "options": [
                "A. By installing filter capacitors in series with the alternator leads",
                "B. By installing a noise suppression resistor and a blocking capacitor at the battery",
                "C. By installing a high-pass filter in series with the radio’s power lead and a low-pass filter in parallel with the antenna feed line",
                "D. By installing ferrite chokes on the charging system leads"
            ],
            "answer": "D. By installing ferrite chokes on the charging system leads"
        },
        {
            "id": "E4E05",
            "question": "What is used to suppress radio frequency interference from a line-driven AC motor?",
            "options": [
                "A. A high-pass filter in series with the motor’s power leads",
                "B. A brute-force AC-line filter in series with the motor’s power leads",
                "C. A bypass capacitor in series with the motor’s field winding",
                "D. A bypass choke in parallel with the motor’s field winding"
            ],
            "answer": "B. A brute-force AC-line filter in series with the motor’s power leads"
        },
        {
            "id": "E4E06",
            "question": "What type of electrical interference can be caused by computer network equipment?",
            "options": [
                "A. A loud AC hum in the audio output of your station’s receiver",
                "B. A clicking noise at intervals of a few seconds",
                "C. The appearance of unstable modulated or unmodulated signals at specific frequencies",
                "D. A whining-type noise that continually pulses off and on"
            ],
            "answer": "C. The appearance of unstable modulated or unmodulated signals at specific frequencies"
        },
        {
            "id": "E4E07",
            "question": "Which of the following can cause shielded cables to radiate or receive interference?",
            "options": [
                "A. Low inductance ground connections at both ends of the shield",
                "B. Common-mode currents on the shield and conductors",
                "C. Use of braided shielding material",
                "D. Tying all ground connections to a common point resulting in differential-mode currents in the shield"
            ],
            "answer": "B. Common-mode currents on the shield and conductors"
        },
        {
            "id": "E4E08",
            "question": "What current flows equally on all conductors of an unshielded multiconductor cable?",
            "options": [
                "A. Differential-mode current",
                "B. Common-mode current",
                "C. Reactive current only",
                "D. Magnetically-coupled current only"
            ],
            "answer": "B. Common-mode current"
        },
        {
            "id": "E4E09",
            "question": "What undesirable effect can occur when using a noise blanker?",
            "options": [
                "A. Received audio in the speech range might have an echo effect",
                "B. The audio frequency bandwidth of the received signal might be compressed",
                "C. Strong signals may be distorted and appear to cause spurious emissions",
                "D. FM signals can no longer be demodulated"
            ],
            "answer": "C. Strong signals may be distorted and appear to cause spurious emissions"
        },
        {
            "id": "E4E10",
            "question": "Which of the following can create intermittent loud roaring or buzzing AC line interference?",
            "options": [
                "A. Arcing contacts in a thermostatically controlled device",
                "B. A defective doorbell or doorbell transformer inside a nearby residence",
                "C. A malfunctioning illuminated advertising display",
                "D. All these choices are correct"
            ],
            "answer": "D. All these choices are correct"
        },
        {
            "id": "E4E11",
            "question": "What could be the cause of local AM broadcast band signals combining to generate spurious signals on the MF or HF bands?",
            "options": [
                "A. One or more of the broadcast stations is transmitting an over-modulated signal",
                "B. Nearby corroded metal connections are mixing and reradiating the broadcast signals",
                "C. You are receiving skywave signals from a distant station",
                "D. Your station receiver IF amplifier stage is overloaded"
            ],
            "answer": "B. Nearby corroded metal connections are mixing and reradiating the broadcast signals"
        },
        {
            "id": "E4E12",
            "question": "What causes interference received as a series of carriers at regular intervals across a wide frequency range?",
            "options": [
                "A. Switch-mode power supplies",
                "B. Radar transmitters",
                "C. Wireless security camera transmitters",
                "D. Electric fences"
            ],
            "answer": "A. Switch-mode power supplies"
        },
        {
            "id": "E4E13",
            "question": "Where should a station AC surge protector be installed?",
            "options": [
                "A. At the AC service panel",
                "B. At an AC outlet",
                "C. On the single point ground panel",
                "D. On a ground rod outside the station"
            ],
            "answer": "C. On the single point ground panel"
        },
        {
            "id": "E4E14",
            "question": "What is the purpose of a single point ground panel?",
            "options": [
                "A. Remove AC power in case of a short-circuit",
                "B. Prevent common-mode transients in multi-wire systems",
                "C. Eliminate air gaps between protected and non-protected circuits",
                "D. Ensure all lightning protectors activate at the same time"
            ],
            "answer": "D. Ensure all lightning protectors activate at the same time"
        }
    ]
}
